version: '3.3'

services:
  velocitas:
    build: "."
    ports:
      - "5000"
    restart: "always"
    networks:
      - "velocitas.network"
    deploy:
      replicas: 5
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - velocitas
    ports:
      - "8080:8080"
    networks:
      - "velocitas.network"
networks:
  velocitas.network: