version: '3.3'

services: 
    velocitas:
        build: "."
        ports:
            - "3000"
        restart: "always"
        networks: 
            - "api.network"
        deploy:
            replicas: 5
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - velocitas
        ports: 
            - "80:80"
        networks: 
            - "velocitas.network"
networks: 
    velocitas.network: